--<ScriptOptions statementTerminator=";"/>

CREATE ROLE "ROLEADMIN";

CREATE ROLE "ROLEAPP";

CREATE DATABASE PARTITION GROUP "PARTICION1" ON DBPARTITIONNUMS (0);

CREATE REGULAR TABLESPACE "TABLESPACE"
	IN DATABASE PARTITION GROUP "PARTICION1"
	MANAGED BY SYSTEM
	USING ('containers1') ON DBPARTITIONNUM (0)
	EXTENTSIZE 64
	PREFETCHSIZE 640
	OVERHEAD 7.5
	TRANSFERRATE 0.06
	DATA TAG NONE;

CREATE SCHEMA "INFO_STUD";

CREATE TABLE "INFO_STUD"."ACTIVITY" (
		"STUDENT_ID" CHAR(10) NOT NULL, 
		"ACTIVITY_ID" CHAR(5) NOT NULL, 
		"JOIN_DATE" DATE
	)
	DATA CAPTURE NONE 
	IN "TABLESPACE"
	COMPRESS NO;

CREATE TABLE "INFO_STUD"."COURSE" (
		"DEPT_ID" CHAR(4), 
		"INSTRUCTOR_ID" CHAR(5), 
		"INSTRUCTOR_NAME" VARCHAR(20), 
		"STUDENT_TOTAL" INTEGER, 
		"COURSE_ID" CHAR(5) NOT NULL, 
		"STUDENT_ID" CHAR(10) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "TABLESPACE"
	COMPRESS NO;

CREATE TABLE "INFO_STUD"."GRADE" (
		"STUDENT_ID" CHAR(10) NOT NULL, 
		"COURSE_ID" CHAR(8) NOT NULL, 
		"SCORE_PASS_FAIL" CHAR(1) NOT NULL, 
		"SCORE_TOTAL" DECIMAL(3 , 0) NOT NULL, 
		"ATTRIBUTE1" CHAR(5) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "TABLESPACE"
	COMPRESS NO;

CREATE TABLE "INFO_STUD"."STUDENT" (
		"STUDENT_ID" CHAR(10) NOT NULL, 
		"FIRST_NAME" VARCHAR(20) NOT NULL, 
		"LAST_NAME" VARCHAR(128) NOT NULL, 
		"START_DATE" DATE, 
		"GRADUATION_DATE" DATE, 
		"STUDENT_SSN" CHAR(11), 
		"EMAIL_ADD" VARCHAR(128)
	)
	DATA CAPTURE NONE 
	IN "TABLESPACE"
	COMPRESS NO;

CREATE INDEX "INFO_STUD"."ACTIVITY_STUDENT_ID_IDX"
	ON "INFO_STUD"."ACTIVITY"
	("STUDENT_ID"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS NO;

CREATE INDEX "INFO_STUD"."COURSE_STUDENT_ID_IDX"
	ON "INFO_STUD"."COURSE"
	("STUDENT_ID"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS NO;

CREATE INDEX "INFO_STUD"."GRADE_COURSE_ID_IDX"
	ON "INFO_STUD"."GRADE"
	("COURSE_ID"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS NO;

CREATE INDEX "INFO_STUD"."GRADE_STUDENT_ID_IDX"
	ON "INFO_STUD"."GRADE"
	("STUDENT_ID"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS NO;

ALTER TABLE "INFO_STUD"."ACTIVITY" ADD CONSTRAINT "ACTIVITY_PK" PRIMARY KEY
	("STUDENT_ID", 
	 "ACTIVITY_ID");

ALTER TABLE "INFO_STUD"."COURSE" ADD CONSTRAINT "COURSE_PK" PRIMARY KEY
	("COURSE_ID");

ALTER TABLE "INFO_STUD"."GRADE" ADD CONSTRAINT "GRADE_PK" PRIMARY KEY
	("COURSE_ID", 
	 "STUDENT_ID", 
	 "ATTRIBUTE1");

ALTER TABLE "INFO_STUD"."STUDENT" ADD CONSTRAINT "STUDENT_GRADUATION_DATE_CK" CHECK (GRADUATION_DATE > START_DATE);

ALTER TABLE "INFO_STUD"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY
	("STUDENT_ID");

ALTER TABLE "INFO_STUD"."ACTIVITY" ADD CONSTRAINT "ACTIVITY_STUDENT_FK" FOREIGN KEY
	("STUDENT_ID")
	REFERENCES "INFO_STUD"."STUDENT"
	("STUDENT_ID");

ALTER TABLE "INFO_STUD"."COURSE" ADD CONSTRAINT "COURSE_STUDENT_FK" FOREIGN KEY
	("STUDENT_ID")
	REFERENCES "INFO_STUD"."STUDENT"
	("STUDENT_ID");

ALTER TABLE "INFO_STUD"."GRADE" ADD CONSTRAINT "GRADE_COURSE_FK" FOREIGN KEY
	("COURSE_ID")
	REFERENCES "INFO_STUD"."COURSE"
	("COURSE_ID");

ALTER TABLE "INFO_STUD"."GRADE" ADD CONSTRAINT "GRADE_STUDENT_FK" FOREIGN KEY
	("STUDENT_ID")
	REFERENCES "INFO_STUD"."STUDENT"
	("STUDENT_ID");

GRANT "ROLEADMIN" TO USER "USERADMIN1";

GRANT "ROLEAPP" TO USER "USERAPP1";

GRANT "ROLEAPP" TO USER "USERAPP2";

GRANT ACCESSCTRL ON DATABASE  TO ROLE "ROLEADMIN";

GRANT BINDADD ON DATABASE  TO ROLE "ROLEAPP";

GRANT CONNECT ON DATABASE  TO ROLE "ROLEADMIN";

GRANT CONNECT ON DATABASE  TO ROLE "ROLEAPP";

GRANT CONNECT ON DATABASE  TO USER "USERADMIN1";

GRANT CONNECT ON DATABASE  TO USER "USERAPP1";

GRANT CONNECT ON DATABASE  TO USER "USERAPP2";

GRANT CREATETAB ON DATABASE  TO ROLE "ROLEAPP";

GRANT CREATE_EXTERNAL_ROUTINE ON DATABASE  TO ROLE "ROLEAPP";

GRANT DATAACCESS ON DATABASE  TO ROLE "ROLEADMIN";

GRANT DBADM ON DATABASE  TO ROLE "ROLEADMIN";

GRANT IMPLICIT_SCHEMA ON DATABASE  TO ROLE "ROLEAPP";

GRANT LOAD ON DATABASE  TO ROLE "ROLEADMIN";

GRANT LOAD ON DATABASE  TO ROLE "ROLEAPP"; 

GRANT SECADM ON DATABASE  TO ROLE "ROLEADMIN";

GRANT SQLADM ON DATABASE  TO ROLE "ROLEADMIN";

GRANT WLMADM ON DATABASE  TO ROLE "ROLEADMIN";

