SELECT S0.STUDENT_ID  AS  STUDENT_ID,
        S0.ACTIVITY_ID  AS  ACTIVITY_ID,
        CAST(NULL  AS  DATE)  AS  JOIN_DATE
FROM  SAMPLE_STUDENT.STUDENT_LIFE.ACTIVITY S0;

SELECT S1.DEPT_ID  AS  DEPT_ID,
        CAST(NULL  AS  CHAR(5))  AS  INSTRUCTOR_ID,
        CAST(NULL  AS  VARCHAR(20))  AS  INSTRUCTOR_NAME,
        CAST(NULL  AS  INTEGER)  AS  STUDENT_TOTAL,
        CAST(''  AS  CHAR(5))  AS  COURSE_ID,
        CAST(''  AS  CHAR(10))  AS  STUDENT_ID,
        CAST(NULL  AS  CHAR(30))  AS  INSTRUCTOR_PHONE
FROM  SAMPLE_STUDENT.STUDENT_LIFE.COURSE S1;

SELECT S2.STUDENT_ID  AS  STUDENT_ID,
        CAST(''  AS  CHAR(8))  AS  COURSE_ID,
        CAST(''  AS  CHAR(1))  AS  SCORE_PASS_FAIL,
        CAST(NULL  AS  DECIMAL)  AS  SCORE_TOTAL,
        CAST(''  AS  CHAR(5))  AS  ATTRIBUTE1
FROM  SAMPLE_STUDENT.STUDENT_LIFE.GRADE S2;

SELECT UCASE(S3.FIRST_NAME)  AS  FIRST_NAME,
        CAST(''  AS  VARCHAR(128))  AS  LAST_NAME,
        CAST(''  AS  CHAR(10))  AS  STUDENT_ID,
        CAST(NULL  AS  CHAR(11))  AS  STUDENT_SSN,
        CAST(NULL  AS  VARCHAR(128))  AS  EMAIL_ADD,
        CAST(NULL  AS  DATE)  AS  START_DATE,
        CAST(NULL  AS  DATE)  AS  GRADUATION_DATE,
        CAST(NULL  AS  CHAR(30))  AS  STUDENT_PHONE
FROM  SAMPLE_STUDENT.STUDENT_LIFE.STUDENT S3;

