--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "STUDENT_LIFE"."ACTIVITY" DROP CONSTRAINT "ACTIVITY_STUDENT_FK";

ALTER TABLE "STUDENT_LIFE"."COURSE" DROP CONSTRAINT "COURSE_STUDENT_FK";

ALTER TABLE "STUDENT_LIFE"."GRADE" DROP CONSTRAINT "GRADE_COURSE_FK";

ALTER TABLE "STUDENT_LIFE"."GRADE" DROP CONSTRAINT "GRADE_STUDENT_FK";

ALTER TABLE "STUDENT_LIFE"."ACTIVITY" DROP CONSTRAINT "ACTIVITY_PK";

ALTER TABLE "STUDENT_LIFE"."COURSE" DROP CONSTRAINT "COURSE_PK";

ALTER TABLE "STUDENT_LIFE"."GRADE" DROP CONSTRAINT "GRADE_PK";

ALTER TABLE "STUDENT_LIFE"."STUDENT" DROP CONSTRAINT "STUDENT_PK";

ALTER TABLE "STUDENT_LIFE"."STUDENT" DROP CONSTRAINT "STUDENT_START_DATE_CK";

DROP TABLE "STUDENT_LIFE"."ACTIVITY";

DROP TABLE "STUDENT_LIFE"."COURSE";

DROP TABLE "STUDENT_LIFE"."GRADE";

DROP TABLE "STUDENT_LIFE"."STUDENT";

DROP SCHEMA "STUDENT_LIFE" RESTRICT;

CREATE SCHEMA "STUDENT_LIFE";

CREATE TABLE "STUDENT_LIFE"."ACTIVITY" (
		"STUDENT_ID" CHAR(10) NOT NULL, 
		"ACTIVITY_ID" CHAR(5) NOT NULL, 
		"JOIN_DATE" DATE, 
		CONSTRAINT "ACTIVITY_PK" PRIMARY KEY
		("STUDENT_ID", 
		 "ACTIVITY_ID")
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "STUDENT_LIFE"."COURSE" (
		"DEPT_ID" CHAR(4), 
		"INSTRUCTOR_ID" CHAR(5), 
		"INSTRUCTOR_NAME OR NM" VARCHAR(20), 
		"STUDENT_TOTAL" INTEGER, 
		"COURSE_ID" CHAR(5) NOT NULL, 
		"STUDENT_ID" CHAR(10) NOT NULL, 
		CONSTRAINT "COURSE_PK" PRIMARY KEY
		("COURSE_ID")
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "STUDENT_LIFE"."GRADE" (
		"STUDENT_ID" CHAR(10) NOT NULL, 
		"COURSE_ID" CHAR(8) NOT NULL, 
		"SCORE_PASS_FAIL" CHAR(1) NOT NULL, 
		"SCORE_TOTAL" DECIMAL(3 , 0) NOT NULL, 
		"ATTRIBUTE1" CHAR(5) NOT NULL, 
		CONSTRAINT "GRADE_PK" PRIMARY KEY
		("COURSE_ID", 
		 "STUDENT_ID", 
		 "ATTRIBUTE1")
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "STUDENT_LIFE"."STUDENT" (
		"FIRST_NAME" VARCHAR(20) NOT NULL, 
		"LAST_NAME" VARCHAR(128) NOT NULL, 
		"STUDENT_ID" CHAR(10) NOT NULL, 
		"STUDENT_SSN" CHAR(11), 
		"EMAIL_ADD" VARCHAR(128), 
		"START_DATE" DATE, 
		"GRADUATION_DATE" DATE, 
		CONSTRAINT "STUDENT_PK" PRIMARY KEY
		("STUDENT_ID")
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "STUDENT_LIFE"."STUDENT" ADD CONSTRAINT "STUDENT_START_DATE_CK" CHECK (GRADUATION_DATE > START_DATE);

ALTER TABLE "STUDENT_LIFE"."ACTIVITY" ADD CONSTRAINT "ACTIVITY_STUDENT_FK" FOREIGN KEY
	("STUDENT_ID")
	REFERENCES "STUDENT_LIFE"."STUDENT"
	("STUDENT_ID");

ALTER TABLE "STUDENT_LIFE"."COURSE" ADD CONSTRAINT "COURSE_STUDENT_FK" FOREIGN KEY
	("STUDENT_ID")
	REFERENCES "STUDENT_LIFE"."STUDENT"
	("STUDENT_ID");

ALTER TABLE "STUDENT_LIFE"."GRADE" ADD CONSTRAINT "GRADE_COURSE_FK" FOREIGN KEY
	("COURSE_ID")
	REFERENCES "STUDENT_LIFE"."COURSE"
	("COURSE_ID");

ALTER TABLE "STUDENT_LIFE"."GRADE" ADD CONSTRAINT "GRADE_STUDENT_FK" FOREIGN KEY
	("STUDENT_ID")
	REFERENCES "STUDENT_LIFE"."STUDENT"
	("STUDENT_ID");

