SELECT S0.STUDENT_ID  AS  STUDENT_ID,
        UCASE(S0.FIRST_NAME/FIRST_NAME)  AS  FIRST_NAME,
        S0.LAST_NAME  AS  LAST_NAME,
        S0.START_DATE  AS  START_DATE,
        S0.GRADUATION_DATE  AS  GRADUATION_DATE,
        S0.STUDENT_SSN  AS  STUDENT_SSN,
        S0.EMAIL_ADD  AS  EMAIL_ADD
FROM  SAMPLE.STUDENT_LIFE.STUDENT S0;

SELECT S1.STUDENT_ID  AS  STUDENT_ID,
        S1.ACTIVITY_ID  AS  ACTIVITY_ID,
        S1.JOIN_DATE  AS  JOIN_DATE,
        CAST(NULL  AS  CHAR(5))  AS  NUEVA
FROM  SAMPLE.STUDENT_LIFE.ACTIVITY S1;

SELECT S2.DEPT_ID  AS  DEPT_ID,
        S2.INSTRUCTOR_ID  AS  INSTRUCTOR_ID,
        S2.INSTRUCTOR_NAME  AS  INSTRUCTOR_NAME,
        S2.STUDENT_TOTAL  AS  STUDENT_TOTAL,
        S2.COURSE_ID  AS  COURSE_ID,
        S2.STUDENT_ID  AS  STUDENT_ID
FROM  SAMPLE.STUDENT_LIFE.COURSE S2;

SELECT S3.STUDENT_ID  AS  STUDENT_ID,
        S3.COURSE_ID  AS  COURSE_ID,
        S3.SCORE_PASS_FAIL  AS  SCORE_PASS_FAIL,
        S3.SCORE_TOTAL  AS  SCORE_TOTAL,
        S3.ATTRIBUTE1  AS  ATTRIBUTE1
FROM  SAMPLE.STUDENT_LIFE.GRADE S3;

